### ISSUE TITLE
Translation to other languages?

### ISSUE THREAD

**Issue by Mattio-cmd** [paulopacitti/gruvbox-factory#10]
I enjoy this utility, simple and easy to use. So i was thinking about translating it to more languages so more people could use it. I personally just speak 2 languages fluently so i could translate it to the other language. If you think its a good idea, let me know and ill start working on it as soon as a I have time :)

**Comment by paulopacitti** [comment]
Hey @Mattio-cmd , sorry for the delay! I think that as a CLI and English being the current global language, I'd say that mainting in English would be better. But, I think it would be a great if we have documentation in other languages 😄 What do you think?

**Comment by Mattio-cmd** [comment]
I thinks it is a great idea. So, should i translate the README and stuff?

**Comment by paulopacitti** [comment]
Feel free to to do it :) I'll close this issue for the sake of maintenance
