### ISSUE TITLE
video

### ISSUE THREAD

**Issue by Javi3y** [paulopacitti/gruvbox-factory#11]
can you use this to convert videos or not?
if not can you add the feature if it's possible?

**Comment by paulopacitti** [comment]
Actually, it's not possible 😕 This tool was based on [ImageGoNord](https://github.com/Schrodinger-Hat/ImageGoNord) and it was built to handle images only. A work around would be to use [ffmpeg](https://www.ffmpeg.org/), get each frame, run `gruvbox-factory` in each of them and then merge the frames again. Or you can just do a color grading similar to the gruvbox palette hahahaha
