### ISSUE TITLE
Does not Recognise or finds the wallpaper 

### ISSUE THREAD

**Issue by tanaybhomia** [paulopacitti/gruvbox-factory#14]
When ever I fire the gruvbox factory it shows everything and is installed just fine but when I enter the image path from home it does not find any image and exits

![image](https://user-images.githubusercontent.com/71910027/150471401-3690007e-15f7-46b0-8de6-86590b102c66.png)

Is their any way you can add a gui to select the image when you enter the facotry or tell me what error is this ?

**Comment by paulopacitti** [comment]
Hello @Deottive 👋🏻 `gruvbox-factory` uses relative paths. This way, you have to run the script in the with a relative path from where you are at the terminal :)
