### ISSUE TITLE
WARNING: The script cmark is installed in '/home/user/.local/bin' which is not on PATH.

### ISSUE THREAD

**Issue by Noob-linux-user** [paulopacitti/gruvbox-factory#18]
This error msg showed when i ran the installation lines.
I am using Linux mint 20.3
There is another report of this anomaly but no response is there.

* the terminal processes looks like this *

pip3 install gruvbox-factory
Collecting gruvbox-factory
  Downloading gruvbox_factory-1.0.0-py3-none-any.whl (5.3 kB)
Collecting rich
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     |████████████████████████████████| 237 kB 390 kB/s 
Collecting image-go-nord
  Downloading image_go_nord-0.1.5-py3-none-any.whl (11 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 711 kB/s 
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 368 kB/s 
Collecting typing-extensions<5.0,>=4.0.0; python_version < "3.9"
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from image-go-nord->gruvbox-factory) (7.0.0)
Installing collected packages: commonmark, pygments, typing-extensions, rich, image-go-nord, gruvbox-factory
  WARNING: The script cmark is installed in '/home/amlan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/amlan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script gruvbox-factory is installed in '/home/amlan/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed commonmark-0.9.1 gruvbox-factory-1.0.0 image-go-nord-0.1.5 pygments-2.13.0 rich-12.6.0 typing-extensions-4.4.0

**Comment by jmacias1503** [comment]
As what I experienced, just move the script in that file to `/usr/local/bin` and you are ready to go and use the script wherever you want

**Comment by paulopacitti** [comment]
Alright, it seems it was fixed. Closing it
