### ISSUE TITLE
Shutting down after error

### ISSUE THREAD

**Issue by ghost** [paulopacitti/gruvbox-factory#19]
I think instead of having the tool shut down (after you enter a wrong color palette name or file that doesn't exist), the tool shouldn't shut down but instead restart. It's kinda annoying to retype everything.

A bonus feature would have the tool restarted at the same step, so basically it'd ask for the information repeatedly until valid info is given.

**Comment by paulopacitti** [comment]
Hmmm, it could be a good idea. Feel free to open a PR if you figure it out a good way to do this :)

**Comment by ghost** [comment]
> Hmmm, it could be a good idea. Feel free to open a PR if you figure it out a good way to do this :)

Yeah I'll try doing that when I can code and have time :D
New to CLIs so this will be fun!
