### ISSUE TITLE
Accept filepath as argument

### ISSUE THREAD

**Issue by marcoaaguiar** [paulopacitti/gruvbox-factory#2]
The tool already has a good-looking CLI, but it would be nice to pass the target file as an argument to the script.

The use case is allowing for tab completion or even scripting for multiple files.

Great tool btw :)

**Comment by paulopacitti** [comment]
Thanks for opening an issue and for the feedback @marcoaaguiar ✨  I've shared this tool on Reddit and many people suggested this kind of feature, so I'll implement in the next future, but I'm not currently available for developing this right now 😕, so it'll take some time. If you need this feature faster, feel free to open a PR 💟

**Comment by Gabulhas** [comment]
@paulopacitti this is already solved
