### ISSUE TITLE
Palette names

### ISSUE THREAD

**Issue by ghost** [paulopacitti/gruvbox-factory#20]
The palette names are confusing and not straight-forward for a new user.

These were all my tries until I got the correct palette name  😂
1. panther pink
2. panther
3. 'pink'
4. 'panther pink'
5. pink

I mean it could just be me being dumb, but maybe the instructions could be more clear in the CLI.

**Comment by paulopacitti** [comment]
I tried to create a story behind the colors hahahahaha but you're right. It had been quite some time that I was not using the tool, and even I got confused. I think we could improve with better docks and maybe a `help` command.

**Comment by ghost** [comment]
> I tried to create a story behind the colors hahahahaha but you're right. It had been quite some time that I was not using the tool, and even I got confused. I think we could improve with better docks and maybe a `help` command.

Those sound like good ideas, if I can, I'll make a PR!
