### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by JwanKhalaf** [paulopacitti/gruvbox-factory#23]
Would it be possible to add some install instructions on the README please?

I've just done a fresh Arch install, but I don't have `pip3` and I'm not sure what the easiest way forward would be to use the `gruvbox-factory` tool.

**Comment by paulopacitti** [comment]
You have to install `python` first with `pip`, which is the package manager for `python`. Then you will be able to install :)

**Comment by YuvanMichaelVivenzi** [comment]
Arch by default now uses "Externally Managed Packages" for pip, Ex: "sudo pacman -S 'python-pip'" And pip packages same way. So I don't think this will work anymore?

**Comment by paulopacitti** [comment]
this also happens with other Linux distros, but each one has a specific way of doing this. Still, the package is registered on [pip](https://pypi.org/), so that's the way to indicate users how to download it. Closing this issue for now
