### ISSUE TITLE
KeyError: '' 

### ISSUE THREAD

**Issue by marcelofern** [paulopacitti/gruvbox-factory#3]
I am having the following error when converting an image:
![image](https://user-images.githubusercontent.com/17491689/114131850-70e21000-9957-11eb-9e99-2724101da759.png)

libs:
image-go-nord==0.1.1
gruvbox-factory==0.1.1
rich==10.1.0

Python 3.9.

**Comment by marcelofern** [comment]
After having a quick scan through the nordic package I found this:
![image](https://user-images.githubusercontent.com/17491689/114132848-3aa59000-9959-11eb-8173-3a9bfec2f17d.png)

Alright, no idea why this line is in there. I was able to circumvent this anomaly by adding a `gruvbox_factory.PALETTE_DATA[''] = [1,2,3]` somewhere in the __main__.py file after the `add_gruvbox_palette` call and before the `convert_image` call.

Not keen on this solution by any means, but it might give you a few clues to fix the problem.

**Comment by paulopacitti** [comment]
Thanks for opening an issue @marcelofern ✨ I will check on this later, thanks for investigating and sharing some tips of what might be causing the bug 🐛 If you find a solution, feel free to share it and open a PR 💟

**Comment by marcelofern** [comment]
No worries. I did some investigation and the root cause comes from this issue: https://github.com/Schrodinger-Hat/ImageGoNord-pip/issues/5

It seems like the proper fix is to fix that library instead. So I submitted a new pull request. In the mean while, I'd suggest to add a blank line at the end of `gruvbox.txt`. Here is the PR:

**Comment by marcelofern** [comment]
@paulopacitti  in the meanwhile, you can merge this PR: https://github.com/paulopacitti/gruvbox-factory/pull/4 so that the lib isn't broken for people installing it from yesterday onwards. I've tested it locally and it fixes the problem, but I'd suggest testing on your local as well to confirm it.

**Comment by paulopacitti** [comment]
awesome @marcelofern! 💯 Thanks for fixing [Schrodinger-Hat/ImageGoNord](https://github.com/Schrodinger-Hat/ImageGoNord-pip) and opening a PR fixing it here too! I'll merge it for sure 😉
