### ISSUE TITLE
 Unable to process any image - Getting Type Error.

### ISSUE THREAD

**Issue by gennarocc** [paulopacitti/gruvbox-factory#5]
Ive used this program in the past with success but whipped it out again and I've been having issues. Perhaps Im just doing something wrong.

I get the following after providing a image.
```
Traceback (most recent call last):
  File "/home/gcc/.local/bin/gruvbox-factory", line 8, in <module>
    sys.exit(main())
  File "/home/gcc/.local/lib/python3.9/site-packages/factory/__main__.py", line 32, in main
    gruvbox_factory.convert_image(image, save_path=('gruvbox_' + image_file))
  File "/home/gcc/.local/lib/python3.9/site-packages/ImageGoNord/GoNord.py", line 425, in convert_image
    self.converted_loop(is_rgba, pixels, original_pixels, image.size[0], image.size[1])
  File "/home/gcc/.local/lib/python3.9/site-packages/ImageGoNord/GoNord.py", line 399, in converted_loop
    pixels[row, col] = tuple(colors_list)
TypeError: function takes at least 3 arguments (0 given)
```
Here is my python version: 
`pip 20.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)`

**Comment by paulopacitti** [comment]
I think a function might have been refactored in a new version of `ImageGoNord`. Investigating 🔍

**Comment by paulopacitti** [comment]
The color palette file was with 2 extra lines at the end, where it should have only one. Now it's fixed 💪🏻 Already uploaded a new version (`0.1.3`) to `pip`. Install this version, it should work now 😉

**Comment by gennarocc** [comment]
Thanks for getting back to me so quick and thanks for the fix!

**Comment by paulopacitti** [comment]
Thank you for noticing the bug 🐛
