### ISSUE TITLE
cli "hipster mode" looks for gruvbox.txt in current directory

### ISSUE THREAD

**Issue by mTvare6** [paulopacitti/gruvbox-factory#8]

**Comment by paulopacitti** [comment]
Thanks for notice this issue! I think I know what have been causing this error, I can fix it in the weekend 😉

**Comment by mTvare6** [comment]
Cool!

**Comment by paulopacitti** [comment]
@mTvare6 fixed! Make sure to update, the fix is available in the current version `v0.1.6` 😉

**Comment by mTvare6** [comment]
Works!
